[package]
name = "microservice-with-rust"
version = "0.1.0"
authors = ["Henry Hao <haoyixian1994@hotmail.com>"]
edition = "2018"
description = "This is repo is used to track my learning with 'Hands-on Microservice with Rust'"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12"
rand = "0.5"
failure = "0.1"
futures = "0.1"
tokio =" 0.1"
lazy_static = "1.0"
regex = "1.0"
hyper-staticfile = "0.4"
