[package]
name = "microservice-with-rust"
version = "0.1.0"
authors = ["Henry Hao <haoyixian1994@hotmail.com>"]
edition = "2018"
description = "This is repo is used to track my learning with 'Hands-on Microservice with Rust'"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1"
hyper = "0.12"
rand = "0.5"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
failure = "0.1"
base64 = "0.13"
base64-serde = "0.6"
queryst = "2.0"
serde_cbor = "0.8"
quick-xml = { version = "0.20", features = ["serialize"]}
