[package]
name = "microservice-with-rust"
version = "0.1.0"
authors = ["Henry Hao <haoyixian1994@hotmail.com>"]
edition = "2018"
description = "This is repo is used to track my learning with 'Hands-on Microservice with Rust'"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
chrono = {version = "^0.4", features = ["serde"] }
diesel = { version = "^1.1.0", features = ["postgres", "chrono", "r2d2"] }
failure = "0.1"
r2d2 = "0.8"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.5", features = ["serde", "v4"] }
