[package]
name = "microservice-with-rust"
version = "0.1.0"
authors = ["Henry Hao <haoyixian1994@hotmail.com>"]
edition = "2018"
description = "This is repo is used to track my learning with 'Hands-on Microservice with Rust'"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13"
rand = "0.8"
futures = "0.3.8"
tokio = {version = "0.2", features=["full"] }
lazy_static = "1.4"
regex = "1.4.2"
hyper-staticfile = "0.5.3"
