[package]
name = "microservice-with-rust"
version = "0.1.0"
authors = ["Henry Hao <haoyixian1994@hotmail.com>"]
edition = "2018"
description = "This is repo is used to track my learning with 'Hands-on Microservice with Rust'"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12"
rand = "0.5"
log = "0.4"
pretty_env_logger = "0.2"
dotenv = "0.13"
clap = "2.32"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
